export const INCREMENT_ALFA    = 'INCREMENT_ALFA';
export const INCREMENT_BRAVO   = 'INCREMENT_BRAVO';
export const INCREMENT_CHARLIE = 'INCREMENT_CHARLIE';
export const INCREMENT_DELTA   = 'INCREMENT_DELTA';
